
// export const CGL_IMPERIUS_SET_OPTIONS      = 'CGL_IMPERIUS_SET_OPTIONS'
// export const CGL_IMPERIUS_RESET            = 'CGL_IMPERIUS_RESET'
// export const CGL_IMPERIUS_HIGHLIGHT_OPTION = 'CGL_IMPERIUS_HIGHLIGHT_OPTION'
// export const CGL_IMPERIUS_REVEAL_ROLE      = 'CGL_IMPERIUS_REVEAL_ROLE'
