
// const
export const LG_LISTS_PAGE_SIZE = 20

// actions
export const LG_LISTS_REQUEST_LOBBY_PAGE = 'LG_LISTS_REQUEST_LOBBY_PAGE'
export const LG_LISTS_REQUEST_GAME_PAGE = 'LG_LISTS_REQUEST_GAME_PAGE'
export const LG_LISTS_SET_LOBBY_LIST = 'LG_LISTS_SET_LOBBY_LIST'
export const LG_LISTS_SET_GAME_LIST =  'LG_LISTS_SET_GAME_LIST'
export const LG_LISTS_SET_RESPONSE = 'LG_LISTS_SET_RESPONSE'
