
export const CGL_CRUCIO_SET_OPTIONS      = 'CGL_CRUCIO_SET_OPTIONS'
export const CGL_CRUCIO_RESET            = 'CGL_CRUCIO_RESET'
export const CGL_CRUCIO_HIGHLIGHT_OPTION = 'CGL_CRUCIO_HIGHLIGHT_OPTION'
export const CGL_CRUCIO_REVEAL_ROLE      = 'CGL_CRUCIO_REVEAL_ROLE'
