
// CGL == Current Game Lobby
// Actions
export const CGL_AVADA_KEDAVRA_RESET                     = "CGL_AVADA_KEDAVRA_RESET"
export const CGL_SET_CANDIDATES_SPELL_AVADA_KEDAVRA      = "CGL_SET_CANDIDATES_SPELL_AVADA_KEDAVRA"
export const CGL_SELECT_VICTIM_AVADA_KEDAVRA             = "CGL_SELECT_VICTIM_AVADA_KEDAVRA"