
export const WS_OPEN_SOCKET = 'WS_OPEN_SOCKET'
export const WS_CLOSE_SOCKET = 'WS_CLOSE_SOCKET'
export const WS_SEND_MESSAGE = 'WS_SEND_MESSAGE'

export const WS_CONNECT_REQUEST = 'WS_CONNECT_REQUEST'
export const WS_CONNECT_SUCCESS = 'WS_CONNECT_SUCCESS'
export const WS_CONNECT_FAILURE = 'WS_CONNECT_FAILURE'
export const WS_DISCONNECT_REQUEST = 'WS_DISCONNECT_REQUEST'
export const WS_DISCONNECT_SUCCESS = 'WS_DISCONNECT_SUCCESS'
export const WS_DISCONNECT_FAILURE = 'WS_DISCONNECT_FAILURE'
export const WS_RECEIVE_MESSAGE = 'WS_RECEIVE_MESSAGE'
export const WS_CONSUME_MESSAGE = 'WS_CONSUME_MESSAGE'
export const REQUEST_AUTH = 'REQUEST_AUTH'
