
export const APPS_ACTIVATE_CHANGE_NICK = 'APPS_ACTIVATE_CHANGE_NICK'
export const APPS_DESACTIVE_CHANGE_NICK = 'APPS_DESACTIVE_CHANGE_NICK'
export const APPS_ACTIVATE_CRUCIO = 'APPS_ACTIVATE_CRUCIO'
export const APPS_DEACTIVE_CRUCIO = 'APPS_DEACTIVE_CRUCIO'
