
export const APPS_ACTIVATE_CHANGE_NICK      = 'APPS_ACTIVATE_CHANGE_NICK'
export const APPS_DEACTIVE_CHANGE_NICK      = 'APPS_DESACTIVE_CHANGE_NICK'
export const APPS_ACTIVATE_CRUCIO           = 'APPS_ACTIVATE_CRUCIO'
export const APPS_DEACTIVE_CRUCIO           = 'APPS_DEACTIVE_CRUCIO'
export const APPS_ACTIVATE_SELECT_DIRECTOR  = 'APPS_ACTIVATE_SELECT_DIRECTOR'
export const APPS_DEACTIVE_SELECT_DIRECTOR  = 'APPS_DEACTIVE_SELECT_DIRECTOR'
