
export const APPS_ACTIVATE_CHANGE_NICK          = 'APPS_ACTIVATE_CHANGE_NICK'
export const APPS_DEACTIVE_CHANGE_NICK          = 'APPS_DEACTIVE_CHANGE_NICK'
export const APPS_ACTIVATE_SELECT_DIRECTOR      = 'APPS_ACTIVATE_SELECT_DIRECTOR'
export const APPS_DEACTIVE_SELECT_DIRECTOR      = 'APPS_DEACTIVE_SELECT_DIRECTOR'
export const APPS_ACTIVATE_AVADA_KEDAVRA        = 'APPS_ACTIVATE_AVADA_KEDAVRA'
export const APPS_DEACTIVATE_AVADA_KEDAVRA      = 'APPS_DEACTIVATE_AVADA_KEDAVRA'
