
// Action Types
export const CHANGE_SCREEN = 'CHANGE_SCREEN'

// Component Types
export const LOGIN_COMPONENT = "LOGIN_COMPONENT"
export const REGISTER_COMPONENT = "REGISTER_COMPONENT"
export const MAIN_MENU_COMPONENT = "MAIN_MENU_COMPONENT"
export const CREATE_LOBBY_COMPONENT = "CREATE_LOBBY_COMPONENT"
export const JOIN_LOBBY_COMPONENT = "JOIN_LOBBY_COMPONENT"
