
// CGL == Current Game Lobby
export const CGL_SET_LOBBY_INFORMATION = 'CGL_SET_LOBBY_INFORMATION'
export const CGL_SET_GAME_IMFORMATION = 'CGL_SET_GAME_IMFORMATION'
export const CGL_CLEAN_STATE = 'CGL_CLEAN_STATE'
export const CGL_PLAYER_JOINED_LOBBY = 'CGL_PLAYER_JOINED_LOBBY'
export const CGL_PROCLAIM_PHOENIX = 'CGL_PROCLAIM_PHOENIX'
export const CGL_PROCLAIM_DEATH_EATER = 'CGL_PROCLAIM_DEATH_EATER'
export const CGL_BLOCK_CHAT = 'CGL_BLOCK_CHAT'
export const CGL_UNBLOCK_CHAT = 'CGL_BLOCK_CHAT'
export const CGL_SWITCH_TO_GAME = 'CGL_SWITCH_TO_GAME'
